version: 1.0.{build}
image: Visual Studio 2013
configuration: Release
platform: Mixed Platforms
build:
  project: /Sharkfuscator.csproj
  verbosity: minimal
install:
  - git submodule update --init --recursive
artifacts:
  - path: Release/
    name: Release